version: '2'
services:
  app:
    build:
      context: ./docker-src/app
    container_name: app
    mem_limit: 512M
    ports:
      - 8080:80
      - 8443:443
    volumes:
      - /var/www  # Use this if bg-sync is utilized
#     - .:/var/www  # Use this if bg-sync is not utilized
    env_file: environment
    links:
      - db
    networks:
      - connector

  db:
    image: mariadb:latest
    container_name: db
    mem_limit: 512M
    ports:
      - 3306:3306
    volumes:
      - database:/var/lib/mysql
      - ./docker-src/db/conf:/etc/mysql/conf.d
    env_file: environment
    networks:
      - connector

  bg-sync:
    image: cweagans/bg-sync:latest
    container_name: bg-sync
    volumes:
      - .:/source
    volumes_from:
      - app
    environment:
      - SYNC_DESTINATION=/var/www
      - SYNC_MAX_INOTIFY_WATCHES=50000
      - SYNC_NODELETE_SOURCE=0
    privileged: true
    networks:
      - connector

networks:
  connector: {}

volumes:
  database: {}