version: "3"
services:
  api:
    image: node:8-alpine
    working_dir: /app
    entrypoint: sh -c "yarn && yarn serve"
    ports:
      - 3000:3000
    volumes:
      - .:/app
    environment:
      - NODE_ENV=development
      - NO_DEMO=true
    networks:
      - driveback
    depends_on:
      - db

  db:
    image: postgres:10.4-alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=driveback
      - POSTGRES_USER=driveback
      - POSTGRES_DB=driveback
    networks:
      - driveback

networks:
  driveback:
