version: '3.2'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:3.2.0
    environment:
      - ZOOKEEPER_CLIENT_PORT=32181
      - ZOOKEEPER_TICK_TIME=2000
    ports:
        - "32181:32181"

  kafka:
    image: confluentinc/cp-kafka:3.2.0
    depends_on:
      - zookeeper
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:32181
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
    ports:
      - "9092:9092"

  kafka2:
    image: confluentinc/cp-kafka:3.2.0
    depends_on:
      - zookeeper
    environment:
      - KAFKA_BROKER_ID=2
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:32181
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka2:9093
    ports:
      - "9093:9093"

  kafka3:
    image: confluentinc/cp-kafka:3.2.0
    depends_on:
      - zookeeper
    environment:
      - KAFKA_BROKER_ID=3
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:32181
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka3:9094
    ports:
      - "9094:9094"
