version: '2.1'

services:

    nginx:
      image: nginx:alpine
      restart: unless-stopped
      ports:
        - "80:80"
      networks:
        - web-gateway
        - service-network
      volumes:
        - ./site.conf:/etc/nginx/conf.d/default.conf
      depends_on:
        - baseapp

    baseapp:
      build:
        context: .
        dockerfile: Dockerfile
      restart: unless-stopped
      networks:
        - service-network
      environment:
        BASEAPP_RUN_LEVEL: prod
        BASEAPP_DATABASE_DRIVER: mymysql
        BASEAPP_DATABASE_IMPORT: github.com/ziutek/mymysql/mysql
        BASEAPP_DATABASE_SPEC: tcp:mysqldb:3306*baseapp/dev/dev
      depends_on:
        mysqldb:
          condition: service_healthy

    mysqldb:
      image: mariadb:10.1.22
      restart: unless-stopped
      networks:
        - service-network
      environment:
        MYSQL_DATABASE: baseapp
        MYSQL_ROOT_PASSWORD: root
        MYSQL_USER: dev
        MYSQL_PASSWORD: dev
      healthcheck:
        test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
        timeout: 5s
        retries: 10
      volumes:
        - mysql_data:/var/lib/mysql


networks:

  web-gateway:

  service-network:
    internal: true

volumes:

  mysql_data:
