version: '2'
services: 
  web:
      image: wordpress:latest
      links:
       - mysql
      environment:
        WORDPRESS_DB_USER: ${WP_DB_USER}
        WORDPRESS_DB_PASSWORD: ${WP_DB_PASS}
        WORDPRESS_DB_NAME: ${WP_DB_NAME}
      ports:
       - "${WP_PORT}:80"
      volumes:
       - ./wp-content:/var/www/html/wp-content

  mysql:
      image: mysql:5.7
      environment:
       MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASS}
       MYSQL_DATABASE: ${WP_DB_NAME}
       MYSQL_USER: ${WP_DB_USER}
       MYSQL_PASSWORD: ${WP_DB_PASS}
      volumes:
       - ./mysql:/var/lib/mysql
