version: '3'
services:
  client:
    build:
      context: .
      dockerfile: buildconfig/docker/client/Dockerfile
    ports:
     - "8000:80"
  server:
    build:
      context: .
      dockerfile: buildconfig/docker/server/Dockerfile
    ports:
      - "8080:8080"