version: '3'

services:
  zookeeper:
    image: zookeeper:3.4.12
    ports:
      - 2181:2181
    volumes:
      - zk_data_volume:/data
      - zk_datalog_volume:/datalog

  kafka:
    image: wurstmeister/kafka:2.11-2.0.0
    volumes:
      - kafka-volume:/kafka
    environment:
      JMX_PORT: 9999
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_CREATE_TOPICS: "topic1:10:1,topic2:5:1"
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ADVERTISED_PORT: 9092
    ports:
      - 9092:9092
      - 9999:9999

  manager:
    image: hlebalbau/kafka-manager:1.3.3.18
    ports:
      - 9000:9000
    environment:
      - ZK_HOSTS=zookeeper:2181

volumes:
  zk_data_volume:
  zk_datalog_volume:
  kafka-volume:

