version: '3.2'
services:

  fren-ticketstack-postgres:
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: ticketstack
      PGDATA: /var/lib/postgresql/data/pgdata
    image: postgres:10
    volumes:
      - pgdata:/var/lib/postgresql/data/pgdata

  fren-ticketstack:
    build:
      context: ./
    ports:
      - 8087:8087
    links:
     - fren-ticketstack-postgres:postgres

volumes:
  pgdata:
    driver: local
