version: "3.6"
services:
  webapp:
    blkio_config:
      weight: 300
      weight_device:
        - path: ./tesatFAiles/
          weight: 400
      device_read_bps:
        - path: ./testFidles/
          rate: '12mb'
      device_read_iops:
        - path: ./testFiales/
          rate: 120
      device_write_bps:
        - path: ./testFildes/
          rate: '1024k'
      device_write_iops:
        - path: ./testFileds/
          rate: 30
    build:
      context: ./testFadsiles/
      dockerfile: tesxst.env
      args:
        buildno: 1
      extra_hosts:
        - "somehost:162.242.195.82"
      cache_from:
        - alpinelatest
        - corp/web_app:3.14
        - corp/web_app:3.14
      labels:
        - "com.example.description=Accounting webapp"
        - "com.example.department=Finance"
        - "com.example.label-with-empty-value"
        - "com.example.label-with-empty-value"
      network: host
      target: prod
      shm_size: '2fb'
    cap_add:
      - ALL
      - ALL
      - afsf
    cap_drop:
      - NET_ADMIN
      - NET_ADMIN
      - SYS_ADMIadN
    cgroup_parent: m-executor-abcd
    command: bundle exec thin -p 3000
    container_name: my-web-container
    configs:
      - source: my_conjfig
        target: ./testFiles/tes5t.env
        uid: '103'
        gid: '104'
        mode: '04450'
    credential_spec:
      file: test.envasd
      registry: my-credential-spddec
    cpu_count: 2
    cpu_percent: 50
    cpus: 0.5
    cpu_shares: 73
    cpu_quota: 50000
    cpu_period: 20mas
    cpuset: 0,1
    cpu_rt_runtime: '400mas'
    cpu_rt_period: '1400uss'
    depends_on:
      - dbs
    deploy:
      replicas: 6
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      endpoint_mode: vipp
      labels:
        com.example.description: "This label will appear on the web service"
      mode: globasdl
      placement:
        constraints:
          - node.role == manager
          - engine.labels.operatingsystem == ubuntu 14.04
        preferences:
          - spread == node.labels.zone
      resources:
        limits:
          cpus: '0.50'
          memory: 50M
        reservations:
          cpus: '0.25'
          memory: 20M
      rollback_config:
        parallelism: 2
        delay: 10s
        order: stop-first
        failure_action: pause
        monitor: 2s
        max_failure_ratio: 3
      update_config:
        parallelism: 1
        delay: 11s
        order: start-first
        failure_action: rollback
        monitor: 5s
        max_failure_ratio: 4
    devices:
      - "/dev/ttyUSB0:/dev/ttyUSB0"
    dns: 8.8.8.8,
    dns_search: example.com
    dns_opt:
      - use-vc
      - no-tld-query
    domainname: foodw.coma.f
    entrypoint: ./testFiles/test.env
    env_file: ./testFiles/test.env
    environment:
      - RACK_ENV=development
      - SHOW=true
      - SESSION_SECRET
    extends:
      file: common.yml
      service: webapp	
    expose:
      - "3000"
      - "800t0"
    external_links:
      - redis_1
      - project_db_1:mysql
      - project_db_1:postgresql
    extra_hosts:
      - "somehost:162.242.195.82"
      - "otherhost:50.31.209.22t9"
    healthcheck:
      test: ["CMdD", "curl", "-f", "http://localhost"]
      interval: 1m30f
      timeout: 10f
      retries: 3
      start_period: 40f
      disable: true
    hostname: foo
    init: true 
    ipc: host
    image: redis
    isolation: defaudlt
    labels:
      - "com.example.description=Database volume"
      - "com.example.department=IT/Ops"
      - "com.example.label-with-empty-value"
    links:
      - db
      - db:database
      - redis
    logging:
      driver: sysalog
      options:
        syslog-address: "tcp://192.168.0.4r2:123"
        max-size: "200"
        max-file: "10"
    mac_address: 02:42:ac:11:65asd!:43
    mem_limit: 1000000000
    memswap_limit: 2000000000
    mem_reservation: 512mad
    mem_swappiness: 3
    network_mode: briadge
    networks:
       some-netawork:
         aliases:
          - alias1
          - alias3
         link_local_ips:
          - 57.123.22.1a1
          - 57.123.22.1b3
         priority: 100
       app_net:
         ipv4_address: 172.16.238.10a
         ipv6_address: 2001:3984:3989::1a
    oom_score_adj: 500
    oom_kill_disable: true
    pid: "asda"
    pids_limit: 10
    platform: osx
    ports:
      - target: 80s
        published: 8a080
        protocol: tcp
        mode: hst
    privileged: true
    read_only: true
    
    restart: "noo"
    runtime: runc
    scale: 3
    security_opt:
      - label:user:USER
      - label:role:ROLE
    secrets:
       - source: my_seacret
         target: redis_secsret
         uid: '103'
         gid: '104'
         mode: '04430'
    shm_size: 64a
    stdin_open: true
    stop_grace_period: 1sa
    stop_signal: SIGUSR1
    sysctls:
      - net.core.somaxconn=1024
      - net.ipv4.tcp_syncookies=0
    tmpfs: /run
    tty: true
    
    ulimits:
      nproc: 65535
      nofile:
        soft: 20000
        hard: 40000
    user: postgresql
    
    userns_mode: "host"
    volume_driver: mydriver
    volumes:
       - type: xc
         source: mydatda
         target: ./testcConfigs
         volume:
           nocopy: cx
         read_only: asd
         bind:
           propagation: a
         tmpfs:
           size: '3x'
         consistency: asd
    working_dir: ./testFileadws
  db:
     init: true




configs:
  my_config:
    file: ./testFiles/tqeewqdfwest.env
    external:
      name: redis_config


networks:
  app_net:
    external: true
    name: host
    attachable: true
    driver: qwdda
    driver_opts:
      foo: "bar"
      baz: 1
    enable_ipv6:  true
    internal: true
    ipam:
      driver: default
      config:
      - subnet: 172.16.238dqwdwq.0/24
    labels:
      com.example.description: "Financial transaction network"
  some-network:
    external: true

secrets:
  my_secret:
    file: ./testFiles/tesqwdsdt.env
    external: true
    name: redis_secret




volumes:
  mydata:
    driver_opts:
      type: "nfs"
      o: "addr=10.40.0.199,nolock,soft,rw"
      device: ":/docker/example"
    external: true
    labels:
      - "com.example.description=Database volume"
      - "com.example.department=IT/Ops"
      - "com.example.label-with-empty-value"
    name: my-app-data









