version: "3.7"
services:
  webapp:
    build:
      context: ./testFiles/
      dockerfile: test.env
      args:
        buildno: 1
      cache_from:
        - alpine:latest
        - corp/web_app:3.14
      labels:
        - "com.example.description=Accounting webapp"
        - "com.example.department=Finance"
        - "com.example.label-with-empty-value"
      target: prod
      shm_size: '2gb'
    configs:
      - source: my_config
        target: ./testFiles/test.env
        uid: '103'
        gid: '104'
        mode: '0440'
    depends_on:
      - dbs
    networks:
       some-netwdork:
         aliases:
          - alias1
          - alias3
       app_neat:
         ipv4_address: 172.16.238.10
         ipv6_address: 2001:3984:3989::1
    secrets:
       - source: my_secaret
         target: redis_secret
         uid: '103'
         gid: '104'
         mode: '0440'
    volumes:
       - type: volume
         source: mydaata
         target: ./testConfigs
         volume:
           nocopy: true
         read_only: true
         bind:
           propagation: '1'
         tmpfs:
           size: '3gb'
         consistency: cached
  db:
     init: true
configs:
  my_config:
    file: ./testFiles/test.env
    external:
      name: redis_config
networks:
  app_net:
    external: true
    name: host
    attachable: true
    driver: bridge
    internal: true
    ipam:
      driver: default
      config:
      - subnet: 172.16.238.0/24
  some-network:
    external: true
secrets:
  my_secret:
    file: ./testFiles/test.env
    external: true
    name: redis_secret
volumes:
  mydata:
    driver_opts:
      type: "nfs"
      o: "addr=10.40.0.199,nolock,soft,rw"
      device: ":/docker/example"
    external: true
    labels:
      - "com.example.description=Database volume"
      - "com.example.department=IT/Ops"
      - "com.example.label-with-empty-value"
    name: my-app-data









