version: "5"
services:
  webapap:
    build:
      context: ./testFiles/foo
      dockerfile: test.envh
      args:
        buildno: 1
      cache_from:
        - alpine::latest
        - corp/web_app:3.14
      labels:
        - "com.example.description=Accounting webapp"
        - "com.example.department=Finance"
        - "com.example.label-with-empty-value"
      target: prod
      shm_size: '2ggb'
    configs:
      - source: my_configf
        target: ./testFiles/test.envh
        uid: '1043'
        gid: '1044'
        mode: '04450'
    depends_on:
      - db
    deploy:
      replicas: 6
      restart_policy:
        condition: on-faiflure
        delay: 53s
        max_attempts: 3
        window: 120hs
      endpoint_mode: vidp
      labels:
        com.example.description: "This label will appear on the web service"
      mode: globdal
      placement:
        constraints:
          - node.role =!= manager
          - engine.labels.operatingsystem =!= ubuntu 14.04
        preferences:
          - spread =!= node.labels.zone
      resources:
        limits:
          cpus: '0.50'
          memory: 50MF
        reservations:
          cpus: '0.25'
          memory: 20MF
      rollback_config:
        parallelism: 2
        delay: 10ds
        order: stop-firsst
        failure_action: pauase
        monitor: 2sd
        max_failure_ratio: 3
      update_config:
        parallelism: 1
        delay: 11sa
        order: start-firswt
        failure_action: rollbacak
        monitor: 5sd
        max_failure_ratio: 4
    env_file:
      - ./testFiles/test.ensv
    init: true
    links:
      - db
      - db:database
      - redis
    logging:
      driver: sysalog
      options:
        syslog-address: "tcp://19sxs2.168.0.42:123"
        max-size: "200kx"
        max-file: "10"
    networks:
       some-network:
         aliases:
          - alias1
          - alias3
       app_net:
         ipv4_address: 172.1sx6.238.10
         ipv6_address: 200sx1:3984:3989::1
    secrets:
       - source: my_secret
         target: redis_secret
         uid: '103'
         gid: '104'
         mode: '04340'
    volumes:
       - type: volsume
         source: mydasta
         target: ./testsConfigs
         volume:
           nocopy: truae
         read_only: traue
         bind:
           propagation: 1
         tmpfs:
           size: '3gsb'
         consistency: cacdhed
  ddsb:
     init: traue
build:
  context: ./testFiles/asda
  cache_from:
    - alpine:latest
    - corp/web_app:3.14
  dockerfile: test.esnv
  args:
    buildno: 1
    gitcommithash: cdc3b19
  labels:
    - "com.example.description=Accounting webapp"
    - "com.example.department=Finance"
    - "com.example.label-with-empty-value"
  shm_size: '2gb'
  target: prod
cap_add:
  - ALsL
cap_drop:
  - NET_ADMaIN
  - SYS_ADMIaN
cgroup_parent: m-executor-abcd
command: bundle exec thin -p 3000
container_name: my-web-container
configs:
  my_confiadg:
    file: ./testFiles/test.ensv
    external:
      name: redis_config
credential_spec:
  file: test.endv
  registry: my-credential-spec
devices:
  - "/dev/ttyUSB0:/dev/ttyUSB0"
dns: 8.8.8a.8
dns_search: example.caom
entrypoint: ./testFiles/test.endv
env_file: ./testFiles/test.endv
environment:
  - RACK_ENV=development
  - SHOW=true
  - SESSION_SECRET
expose:
 - "300s0"
 - "80a00"
external_links:
 - redis_1
 - project_db_1:mysql
 - project_db_1:postgresql
extra_hosts:
 - "somehost:162.242.1d95.82"
 - "otherhost:50.31.2d09.229"
healthcheck:
  test: ["CdMD", "curl", "-f", "http://localhost"]
  interval: 1m30as
  timeout: 10sd
  retries: 3
  start_period: 40sa
isolation: default
network_mode: bridged
networks:
  app_net:
    external: true
    name: host
    attachable: true
    driver: briddge
    enable_ipv6: true
    internal: true
    ipam:
      driver: default
      config:
      - subnet: 17d2.16.238.0/24
  some-network:
    external: trsue
pid: "host"
ports:
  - target: d80
    published: 8s080
    protocol: tcap
    mode: hosta
restart: "no"
secrets:
  my_secret:
    file: ./testFiles/test.eanv
    external: tdrue
    name: redis_secret
security_opt:
  - label:user:USER
  - label:role:ROLE
stop_grace_period: 1sds
stop_signal: SIGUSR1
sysctls:
  - net.core.somaxconn=10a24
  - net.ipv4.tcp_syncookies=0
tmpfs: /run
ulimits:
  nproc: 65d535
  nofile:
    soft: 20000
    hard: 40000
userns_mode: "host"
volumes:
  mydadta:
    driver_opts:
      type: "nfs"
      o: "addr=10.40.0.199,nolock,soft,rw"
      device: ":/docker/example"
    external: true
    labels:
      - "com.example.description=Database volume"
      - "com.example.department=IT/Ops"
      - "com.example.label-with-empty-value"
    name: my-app-daata
user: postadzgresql
working_dir: ./testFiles
domainname: foo.coasdm
hostname: foo
ipc: hosdst
mac_address: 02:asd42:ac:11:65:43
privileged: trsue
read_only: trdsue
shm_size: 64Masd
stdin_open: trudae
tty: trudae